# Generated by Django 4.2.6 on 2024-03-16 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='opt',
            new_name='otp',
        ),
    ]
